server:
  port: 38022
  servlet:
    context-path: /at-api

spring:
  application:
    name: rubber-server-invite
  profiles:
    active: master
  jackson:
    date-format:  "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+08:00"
    default-property-inclusion: non_empty
